title = "Quang Chiem"
baseURL = "https://example.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Ho Chi Minh city, Vietnam"
email = "ctquang89@gmail.com"
favicon = "/favicon.ico"
firstName = "Quang"
lastName = "Chiem"
phone = "(+84)789909647"
#profileImage = "images/Quang_PhotoIEEEAccessJournal.png"
profileImage = "https://media.licdn.com/dms/image/C5103AQG6jSDzY9mu3A/profile-displayphoto-shrink_800_800/0/1576319143809?e=1709164800&v=beta&t=8Or7GyY6dB4wBBNw2Msort6tr_k2EJLlCbvsljUel0s"
showQr = true
showContact = false
#sections = ["skills","publications","creations","contributions","experience","education","blog"]
sections = ["skills", "lprojects", "experience", "education"]

[params.google]

#[params.google.analytics]
#trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/ctquang89/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/ctquang89/"
name = "GitHub"

#[[params.handles]]
#link = "https://bitbucket.org/eddiewebb/"
#name = "Bitbucket"
#
#[[params.handles]]
#link = "https://stackoverflow.com/users/story/82880"
#name = "Stack Overflow"
#
#[[params.handles]]
#link = "https://keybase.io/edwardawebb"
#name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"