title = "Chiem Tri Quang"
baseURL = "https://ctquang89.github.io/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[author]
type = "person"
name = "I am Chiem Tri Quang, an AI enthusiast holding a doctoral degree."
jobTitle = "data scientist"
url = "https://www.linkedin.com/in/ctquang89/" 
[params]
author = "I am Chiem Tri Quang, an AI enthusiast holding a doctoral degree."
description = "I am Chiem Tri Quang, an AI researcher and practitioner with over 8 years of experience in advancing artificial intelligence through research and more than 4 years of hands-on industry expertise. With a doctoral degree specializing in Computer Vision and Deep Learning, I possess a robust foundation in Statistics, Computer Science, Data Analytics, Data Modeling, Reinforcement Learning, and emerging Generative AI applications. In addition to my technical acumen, I bring over 4 years of leadership and team management experience, driving innovation, fostering collaboration, and delivering data-driven solutions to address complex business challenges. My passion lies in leveraging cutting-edge AI technologies to create impactful, scalable solutions that empower businesses and enhance user experiences."
address = "Ho Chi Minh city, Vietnam"
jobTitle = "data scientist"
url = "https://www.linkedin.com/in/ctquang89/" 
email = "ctquang89@gmail.com"
favicon = "/favicon.ico"
firstName = "Quang"
lastName = "Chiem"
phone = "(+84)789909647"
profileImage = "/images/Quang.jpg"
aboutImage = "/images/Quang_1.jpg"
Logo = "/images/Quang_3.jpg"
showQr = true
showContact = false
#sections = ["skills","publications","creations","contributions","experience","education","blog"]
sections = ["skills", "lprojects", "experience", "education", "blog", "certifications"]
custom_css = ["/css/custom.css"]

[markup.goldmark.renderer]
unsafe= true

[[params.handles]]
link = "https://www.linkedin.com/in/ctquang89/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/ctquang89/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"